### ISSUE TITLE
Error when using mix setup

### ISSUE THREAD

**Issue by martinodonnell** [fahrinh/blog-labs#1]
I have never used Elixir before but the sync function is exactly what I need. When I run `mix setup`, I get the following error? 

```
11:32:08.223 [error] GenServer #PID<0.375.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for BlogApp.Repo couldn't be created: killed
```

To recreate this I have just cloned your project in my local and ran the following commands
```
brew install elixir
mix setup
```

**Comment by martinodonnell** [comment]
I figured it out. I forgot to run the docker image with the db. Could you the following to your read-me 
```
docker run --name blog-db -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=blog_app_dev -d -p 5432:5432 postgres:12.2
```
